[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
  "openai>=1.12.0",
  "gspread>=5.12.0",
  "oauth2client>=4.1.3",
  "requests>=2.31.0",
  "beautifulsoup4>=4.12.3",
  "flask>=2.3.3"
]